### ISSUE TITLE
6.0手机上扫描一直crash

### ISSUE THREAD

**Issue by sweet2o09** [465857721/IDCardOCR_China#2]
com.kingsoft.idcardocr_china E/Tesseract(native): Could not initialize Tesseract API with language=eng!

**Comment by sweet2o09** [comment]
eng.traineddata这个文件是什么东西

**Comment by 465857721** [comment]
那个文件是 ocr需要的文件，6.0没有适配 权限问题  你给app打开读写sd卡权限就可以

**Comment by sweet2o09** [comment]
权限我肯定是手动开启了,不过还是报错
com.kingsoft.idcardocr_china E/Tesseract(native): Could not initialize Tesseract API with language=eng!
com.kingsoft.idcardocr_china E/com.kingsoft.idcardocr_china.idcardocr.CameraManager: openDriver
com.kingsoft.idcardocr_china E/com.kingsoft.idcardocr_china.idcardocr.CameraManager: Opening camera #0
com.kingsoft.idcardocr_china E/com.kingsoft.idcardocr_china.idcardocr.CameraManager: startPreview
com.kingsoft.idcardocr_china E/AutoFocusManager: Current focus mode 'auto'; use auto focus? true
com.kingsoft.idcardocr_china E/TAG: mScreenW:1920 mScreenH:1080
com.kingsoft.idcardocr_china E/TAG: left:420
com.kingsoft.idcardocr_china E/TAG: top:180
com.kingsoft.idcardocr_china E/TAG: right:1500
com.kingsoft.idcardocr_china E/TAG: bottom:900
com.kingsoft.idcardocr_china A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0xc in tid 25644 (idcardocr_china)

**Comment by sweet2o09** [comment]
eng.traineddata我这边没有...

**Comment by sweet2o09** [comment]
找到问题了,是因为SD卡里面没有相关文件,为什么不能直接用assets目录下的,还要把他保存在SD卡上,保存的时候出错

**Comment by sweet2o09** [comment]
我这边用你的这个Demo,让它自动拷贝eng.traineddata到SD卡,发现拷贝过去的资源大小为0KB,但是我权限都有开启,不知道为什么

**Comment by 465857721** [comment]
请你自己看看源码吧   谢谢
